# Generated by Django 3.1 on 2020-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date_of_checkup', models.CharField(max_length=50)),
                ('pMobile', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('pulse', models.CharField(max_length=50)),
                ('blood_pressure', models.CharField(max_length=50)),
                ('temprature', models.CharField(max_length=50)),
                ('spo2', models.CharField(max_length=50)),
                ('comorbidity_existing_disease', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=50)),
            ],
        ),
    ]
